CREATE TABLE public.site_content (
  section text PRIMARY KEY,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read site_content" ON public.site_content FOR SELECT USING (true);
CREATE POLICY "Authenticated can update site_content" ON public.site_content FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated can insert site_content" ON public.site_content FOR INSERT TO authenticated WITH CHECK (true);

INSERT INTO public.site_content (section, data) VALUES
('hero', '{"name":"Vasiliy Kolesnikov","title_line1":"Industrial AI","title_line2":"Product Leader","subtitle_ru":"Создаю AI-driven продукты для инфраструктуры и аналитики","subtitle_en":"Building AI-driven infrastructure and analytics products","description_ru":"17+ лет опыта в энергетике, инфраструктуре и цифровых продуктах","description_en":"17+ years in energy, infrastructure and digital products"}'::jsonb),
('contact', '{"email":"vasiliy@example.com","phone":"+70000000000","phone_display":"+7 (000) 000-00-00","portfolio_url":"#","description_ru":"Открыт для обсуждения продуктовых ролей, консалтинга и партнёрства в сфере Industrial AI.","description_en":"Open to discuss product roles, consulting, and partnerships in Industrial AI."}'::jsonb),
('vision', '{"title_ru":"Строю будущее","title_en":"Building the future of","highlight":"Infrastructure AI","description_ru":"AI-мониторинг трубопроводов, инфраструктуры и климатических рисков. Применение машинного обучения для предиктивной аналитики промышленных объектов.","description_en":"AI monitoring for pipelines, infrastructure and climate risks. Applying machine learning for predictive analytics of industrial assets."}'::jsonb),
('impact', '{"metrics":[{"value":"+57%","label_ru":"Рост MAU","label_en":"MAU Growth"},{"value":"18","label_ru":"Инженеров в команде","label_en":"Engineers in team"},{"value":"1500+","label_ru":"Пользователей продукта","label_en":"Product users"},{"value":"10+","label_ru":"Фич отправлено","label_en":"Features shipped"},{"value":"-27%","label_ru":"Снижение затрат","label_en":"Cost reduction"},{"value":"+42%","label_ru":"Рост эффективности","label_en":"Efficiency gain"}]}'::jsonb),
('ai', '{"items":[{"title_ru":"AI/LLM технологии","title_en":"Applied AI/LLM Technologies","desc_ru":"RAG, AI-агенты, обработка естественного языка","desc_en":"RAG, AI agents, natural language processing"},{"title_ru":"Data-driven аналитика","title_en":"Data-driven Analytics","desc_ru":"Построение аналитических платформ для 1500+ пользователей","desc_en":"Built analytics platforms for 1500+ users"},{"title_ru":"Автоматизация инсайтов","title_en":"Automated Insight Generation","desc_ru":"AI-генерация отчётов и рекомендаций","desc_en":"AI-powered reports and recommendations"},{"title_ru":"Decision workflows","title_en":"Decision-making Workflows","desc_ru":"Оптимизация процессов принятия решений через AI","desc_en":"AI-enhanced decision-making processes"}]}'::jsonb),
('experience', '{"timeline":[{"company":"Sberbank","role_ru":"Product Owner / Stream Lead","role_en":"Product Owner / Stream Lead","period_ru":"2021 — настоящее время","period_en":"2021 — Present","items_ru":["Руководство аналитической платформой","Рост MAU +57%","Кросс-функциональная команда из 18 инженеров","Внедрение AI/LLM в аналитику"],"items_en":["Led analytics platform","MAU growth +57%","Cross-functional team of 18 engineers","Introduced AI/LLM in analytics"]},{"company":"Yamal LNG","role_ru":"Руководитель геотехнического мониторинга","role_en":"Head of Geotechnical Monitoring","period_ru":"2015 — 2021","period_en":"2015 — 2021","items_ru":["Управление инфраструктурой: трубопроводы, СПГ, электростанция","Снижение затрат на 50%","Разработка моделей оценки рисков"],"items_en":["Managed infrastructure: pipelines, LNG, power plant","Reduced costs by 50%","Developed risk assessment models"]},{"company":"Early Career","company_ru":"Ранний опыт","company_en":"Early Career","role_ru":"Инженер / Специалист","role_en":"Engineer / Specialist","period_ru":"2007 — 2015","period_en":"2007 — 2015","items_ru":["Инженерные и аналитические позиции в энергетике"],"items_en":["Engineering and analytics roles in energy sector"]}]}'::jsonb),
('skills', '{"groups":[{"title":"Product","skills_ru":["Стратегия","Discovery","Roadmap"],"skills_en":["Strategy","Discovery","Roadmap"]},{"title":"AI / Tech","skills_ru":["AI / LLM / RAG","SaaS","Геопространственная аналитика"],"skills_en":["AI / LLM / RAG","SaaS","Geospatial Analytics"]},{"title":"Leadership","skills_ru":["Руководство командой","Работа со стейкхолдерами","Управление рисками"],"skills_en":["Team Leadership","Stakeholder Management","Risk Management"]}]}'::jsonb),
('industries', '{"items":[{"label_ru":"Энергетика","label_en":"Energy"},{"label_ru":"Инфраструктура","label_en":"Infrastructure"},{"label_ru":"AI / Data","label_en":"AI / Data"},{"label_ru":"Climate Tech","label_en":"Climate Tech"}]}'::jsonb);